# before start project please create file "api.config.yml" and paste this configuration
buildPath: build
db:
  mysql:
    host: localhost
    user: root
    password: admin
    database: run
    connectionLimit: 10
server:
  host: localhost
  port: 5000
socket:
  host: localhost
  port: 5001
redis:
  key: socket.io
  host: localhost
  port: 6379
accessControl:
  - http://localhost:4000